name: publish

on:
    push:
        branches:
            - release

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  registry-url: 'https://registry.npmjs.org'
                  always-auth: true
            - name: can publish
              run: npx can-npm-publish --verbose
            - uses: pnpm/action-setup@v4
            - name: install
              run: pnpm i
            - name: build
              run: pnpm build
            - name: publish
              run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
